### ISSUE TITLE
Config: undefined

### ISSUE THREAD

**Issue by zerojuls** [culqi/culqi-prestashop#17]
Hola, estoy teniendo un problema al querer hacer el checkout con el plugin de culqi. Al hacer click en pagar me muestra el mensaje de error:

> Hubo algunos problemas al intentar validar tu compra. Contáctanos para ayudarte.

Y aparte en el inspeccionador me muestra el mensaje `Config: undefined` .

Adjunto las imagenes del error para mayor conocimiento:

![error-culqi_2](https://user-images.githubusercontent.com/8573420/36704971-cf5b6102-1b30-11e8-960e-90ab2be6783e.png)
![error-culqi](https://user-images.githubusercontent.com/8573420/36704972-cf774da4-1b30-11e8-854b-5a039fb1721e.png)

**Comment by LizRuelas** [comment]
Hola 
Este error puede originarse por diversas razones. Para saber exactamente qué es lo que falló ingresa a: 
- Panel Culqi
- Sección Desarrollo
- Sección Api Log
Allí verás cada una de las transacciones enviadas a Culqi y  los mensajes de respuesta, explicando detalladamente el por qué del error. 
Saludos

**Comment by zerojuls** [comment]
Gracias por la respuesta, si en el api log pude encontrar el error por el que no funcionaba y ya lo solucione, gracias!!! 👍
