### ISSUE TITLE
Add support to Prestashop 1.7

### ISSUE THREAD

**Issue by marti1125** [culqi/culqi-prestashop#3]
follow the following links:

http://developers.prestashop.com/module/50-PaymentModules/index.html

http://build.prestashop.com/news/prestashop-1-7-faq/

**Comment by neraun** [comment]
Hey guys, any idea when prestashop 1.7 will be supported by culqi ?

Do you guys need any help ?

**Comment by brayancruces** [comment]
Hi @neraun  

Yes, this plugin supports Prestashop 1.7.
U can download from this link: https://github.com/culqi/culqi-prestashop/tree/prestashop1.7

**Comment by marti1125** [comment]
:v:
