### ISSUE TITLE
Numero de telefono obligatorio

### ISSUE THREAD

**Issue by neraun** [culqi/culqi-prestashop#4]
Hola Chicos,

Gracias por este sistema y su integración super facil !

Estoy probando la integración de Culqi con nuestra tienda prestashop 1.7.

Algunas Mejoras sugeridas :
- El número de teléfono es un campo obligatorio de su API pero no del Prestashop... Lo puedo cambiar en la configuración de prestashop. Para que el número de teléfono es necesario ?
- Si el número de teléfono es obligatorio y que el cliente no lo entro, seria bueno tener un mensaje de error mas explicite... tuve que abrir la consola y los logs de la API para entender lo que había pasado.
- Al proceder el pago tuve algunas errores en la consola 'culqi is not defined'.

**Comment by neraun** [comment]
Huy ! Mi culpa por leer mal la documentacion !

**Comment by marti1125** [comment]
@neraun upss menos mal que lo agregue a la docu :D
