### ISSUE TITLE
No template found for module Culqi

### ISSUE THREAD

**Issue by neraun** [culqi/culqi-prestashop#5]
Hola Chicos,

Cuando la compra ya está procesada, tengo este mensaje, como puedo hacer para que no se vea ?

![image](https://cloud.githubusercontent.com/assets/15424982/23877021/94dd6330-0840-11e7-8035-b0e0993dbd6a.png)

**Comment by LizRuelas** [comment]
Hola @neraun te agradecería proporcionarme la URL de tu pagina web para realizar una prueba ya que no logro obtener  "No template found for module culqi" a integrate@culqi.com

**Comment by neraun** [comment]
Hola,

No te puedo dar la URL, ya que la pagina no esta publicada todavia. Pero te puedo dar el codigo fuente correspondiente:

**Comment by marti1125** [comment]
Hola @neraun parece que esta parte del hook payment return

https://github.com/culqi/culqi-prestashop/blob/prestashop1.7/culqi.php#L178
y que apunta a este template 
https://github.com/culqi/culqi-prestashop/blob/master/views/templates/hook/payment_return.tpl hay que corregir

**Comment by marti1125** [comment]
@neraun listo ya corrigió este issue, gracias!!

**Comment by marti1125** [comment]
new release https://github.com/culqi/culqi-prestashop/releases/tag/v3.0.1

**Comment by marti1125** [comment]
@neraun todo ok?

**Comment by neraun** [comment]
Segun tu codigo fuente si... si ya no hay referencias al template no se deberian encontrar ese error.

**Comment by marti1125** [comment]
@neraun jejejej gracias!
