### ISSUE TITLE
index.php?controller=order:809 Uncaught TypeError: Cannot read property 'user_message' of undefined

### ISSUE THREAD

**Issue by neraun** [culqi/culqi-prestashop#6]
Hola,

Nuevo problemita, cuando selectiono otro metodo de pago (i.e. tranferencia bancaria) tengo el error siguiente en la consola javaScript y no puedo procesar el pago :

```
index.php?controller=order:809 Uncaught TypeError: Cannot read property 'user_message' of undefined
    at charge (index.php?controller=order:809)
    at HTMLButtonElement.<anonymous> (index.php?controller=order:759)
    at HTMLButtonElement.dispatch (bottom-076ab9.js:100)
    at HTMLButtonElement.elemData.handle (bottom-076ab9.js:92)
charge @ index.php?controller=order:809
(anonymous) @ index.php?controller=order:759
dispatch @ bottom-076ab9.js:100
elemData.handle @ bottom-076ab9.js:92
```

Cuando miro al dicho archivo, parece que el error esta en esta linea :

`   showResult('red',Culqi.error.user_message);`

pues parece que el objeto Culqi.error no esta definido...

**Comment by marti1125** [comment]
@neraun me podrias indicar que otro metodo de pago tienes, y subir alguna image por favor

**Comment by marti1125** [comment]
@neraun podrias indicarme como replicar este issue por favor

**Comment by neraun** [comment]
Usamos el modulo de pago con transferencia bancaria. El error ocurre cuando hago click en "pedido con obligacion de pago"

![image](https://cloud.githubusercontent.com/assets/15424982/24222074/20fbe1e0-0f51-11e7-9f65-10785b665fff.png)

**Comment by marti1125** [comment]
@neraun Genial! mañana lo reviso gracias!! por reportarlo :+1:

**Comment by neraun** [comment]
Hola Willy,

Alguna novedad ?

**Comment by marti1125** [comment]
@neraun disculpa el fin de semana lo revisare :'(

**Comment by PabloGero** [comment]
Yo también tengo ese problema y no se que hacer ... ayuda porfa :(

**Comment by PabloGero** [comment]
![image](https://cloud.githubusercontent.com/assets/965376/26072249/7cb2c32a-3970-11e7-9e9c-7d5c77f69f34.png)

Yo tengo el mismo problema en mi tienda : www.pablogeronimo.com/tienda

**Comment by marti1125** [comment]
Hola ya hice los cambios e98f40f  saque uno release https://github.com/culqi/culqi-prestashop/releases/tag/v3.0.2
la forma de pago es mas sencilla anteriomente estaba integrado con los botones de prestashop pero esta dando problemas y funciona bien asi que los quite. solo le dan pagar el boton de culqi y listo

**Comment by marti1125** [comment]
voy a modificar el README indicando los cambios.

**Comment by marti1125** [comment]
@PabloGero @neraun puedo cerrar este issue =?

**Comment by almacen218** [comment]
Buen dia, cuando se podra usar el boton de prestashop, ya que si se hace desde el boton de culqui confunde al cliente, ya que ya no hace click en pedido con obligacion de pago, lo que genera que ya no haya seguimiento del pedido.

**Comment by marti1125** [comment]
hola @almacen218 estamos trabajando en una nueva versión del plugin para integrar el checkout con el botón de pagar de prestashop y no haya confusión. Hemos movido el proyecto de prestashop 1.7 a otro repo https://github.com/culqi/culqi-prestashop-1.7/tree/development

**Comment by PabloGero** [comment]
Todo conforme desde mi lado, se puede cerrar.
